package com.nanobotkt.feature.channels
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.ArrowBack
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.nanobotkt.core.model.NanobotFeatureInfo
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun ChannelsScreen(onBack:()->Unit,viewModel:ChannelsViewModel=hiltViewModel()){val state by viewModel.state.collectAsStateWithLifecycle();var selected by remember{mutableStateOf<NanobotFeatureInfo?>(null)};val channels=state.payload?.features.orEmpty().filter{it.type=="channel"||it.capabilities?.contains("channel")==true};Scaffold(topBar={TopAppBar(title={Text("Channels")},navigationIcon={IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Rounded.ArrowBack,null)}},actions={IconButton(onClick=viewModel::refresh){Icon(Icons.Rounded.Refresh,"Refresh")}})}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){if(state.loading&&state.payload==null)item{CircularProgressIndicator()};state.error?.let{item{Text(it,color=MaterialTheme.colorScheme.error)}};items(channels,key={it.name}){c->ElevatedCard(onClick={selected=c},modifier=Modifier.fillMaxWidth()){ListItem(headlineContent={Text(c.displayName)},supportingContent={Text("${c.status} · ${c.runtimeStatus?:if(c.configured==true)"configured" else "needs setup"}")},trailingContent={Switch(checked=c.enabled,onCheckedChange={viewModel.enabled(c.name,it)},enabled=c.name !in state.pending)})}};if(channels.isEmpty()&&!state.loading)item{Text("No channel integrations are exposed by this gateway.")}}}
 selected?.let{c->ChannelDialog(c,state.pending.contains(c.name),state.validation,state.connection,onDismiss={selected=null},onValidate={viewModel.validate(c.name,it)},onSave={viewModel.configure(c.name,it,true)},onConnect={viewModel.connect(c.name)})}}
@Composable private fun ChannelDialog(channel:NanobotFeatureInfo,pending:Boolean,validation:com.nanobotkt.core.model.ChannelValidationPayload?,connection:com.nanobotkt.core.model.ChannelConnectPayload?,onDismiss:()->Unit,onValidate:(Map<String,String>)->Unit,onSave:(Map<String,String>)->Unit,onConnect:()->Unit){val initial=channel.configValues.orEmpty();var values by remember(channel.name){mutableStateOf(initial)};AlertDialog(onDismissRequest=onDismiss,title={Text(channel.displayName)},text={LazyColumn(Modifier.heightIn(max=520.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text(channel.status)};channel.setup?.fields.orEmpty().forEach{f->item(key=f.key){if(f.kind=="bool")Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(f.field);Switch(values[f.key].toBoolean(),{values=values+(f.key to it.toString())})}else OutlinedTextField(values[f.key].orEmpty(),{values=values+(f.key to it)},Modifier.fillMaxWidth(),label={Text(f.field+(if(f.required)" *" else ""))},singleLine=true)}};validation?.takeIf{it.name==channel.name}?.let{v->item{Text(v.message?:v.status,color=if(v.status=="invalid")MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.primary)};items(v.checks){Text("${it.label}: ${it.status}${it.message?.let{m->" — $m"}.orEmpty()}")}};connection?.let{item{Text("Connection: ${it.status} ${it.message.orEmpty()}")}}}},confirmButton={Row{TextButton(enabled=!pending,onClick={onValidate(values)}){Text("Validate")};TextButton(enabled=!pending,onClick={onSave(values)}){Text("Save & enable")}}},dismissButton={Row{if(channel.name in listOf("whatsapp","telegram","feishu"))TextButton(enabled=!pending,onClick=onConnect){Text("Connect")};TextButton(onClick=onDismiss){Text("Close")}}})}

